<?php

namespace GGY\DataBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function listByAlphabet(){
        return $this->getEntityManager()->createQuery("SELECT c from GGYDataBundle:Category c order by c.title ASC")->getResult();
    }
}
