<?php

namespace GGY\DataBundle\Repository;

/**
 * GifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GifRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategorySlug($slug)
    {
        return $this->getEntityManager()->createQuery("SELECT g from GGYDataBundle:Gif g order by c.title ASC")->getResult();
    }
}
