<?php

namespace GGY\DataBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function listByAlphabet(){
        return $this->getEntityManager()->createQuery("SELECT t from GGYDataBundle:Tag t order by t.title ASC")->getResult();
    }
}
