ggy_app:
    resource: "@GGYAppBundle/Resources/config/routing.yml"
    prefix:   /
ggy_api_gif:
    type: rest
    prefix: /api
    resource: GGY\ApiBundle\Controller\GifController
ggy_api_category:
    type: rest
    prefix: /api
    resource: GGY\ApiBundle\Controller\CategoryController
ggy_api_tag:
    type: rest
    prefix: /api
    resource: GGY\ApiBundle\Controller\TagController