gif:
    resource: GGY\AppBundle\Controller\GifController
    type:     annotation
categories:
    resource: GGY\AppBundle\Controller\CategoriesController
    type:     annotation
    prefix:   /categories

