gif:
    resource: GGY\AppBundle\Controller\GifController
    type:     annotation
category:
    resource: GGY\AppBundle\Controller\CategoryController
    type:     annotation
    prefix:   /categories
tag:
    resource: GGY\AppBundle\Controller\TagController
    type:     annotation
    prefix:   /tags